AllCops:
  Exclude:
    - tmp/**

ClassAndModuleChildren:
  Enabled: false

Documentation:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

RescueModifier:
  Enabled: false

SignalException:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false
