AllCops:
  Excludes:
    - tmp/**

Documentation:
  Enabled: false

LineLength:
  Enabled: false

ParenthesesAsGroupedExpression:
  Enabled: false

HashSyntax:
  Enabled: false

SignalException:
  Enabled: false
